apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-frontend
  labels:
    app: coit-frontend
spec:
  template:
    spec:
      containers:
        - name: coit-frontend
          env:
          - name: POSTGRESS_PASSWORD
            value: DEVOPS123POST
